/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class flex_weightlearner_LbfgsWeightLearnerJNI */

#ifndef _Included_flex_weightlearner_LbfgsWeightLearnerJNI
#define _Included_flex_weightlearner_LbfgsWeightLearnerJNI
#include <jni.h>

#include <weightlearner.h>

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     flex_weightlearner_LbfgsWeightLearnerJNI
 * Method:    learnWeights
 * Signature: (JJI[II[D)V
 */
JNIEXPORT void JNICALL Java_flex_weightlearner_LbfgsWeightLearnerJNI_learnWeightsL1
  (JNIEnv *, jclass, jlong, jlong, jint, jintArray, jint, jdoubleArray, jdouble jl1Const);
  
JNIEXPORT void JNICALL Java_flex_weightlearner_LbfgsWeightLearnerJNI_learnWeights
  (JNIEnv *, jclass, jlong, jlong, jint, jintArray, jint, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
